/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaTokenRouteImport } from './routes/wa.$token'
import { Route as ResultScoreIdRouteImport } from './routes/result.$scoreId'
import { Route as ApiWaResultRouteImport } from './routes/api/wa-result'
import { Route as ApiWaJobsRouteImport } from './routes/api/wa-jobs'
import { Route as ApiResultSessionRouteImport } from './routes/api/result-session'
import { Route as ApiResultCardRouteImport } from './routes/api/result-card'
import { Route as ApiRationalizationTargetsRouteImport } from './routes/api/rationalization-targets'
import { Route as ApiAdminSkdReviewRouteImport } from './routes/api/admin/skd-review'
import { Route as ApiAdminSkdPdfRouteImport } from './routes/api/admin/skd-pdf'
import { Route as ApiAdminSkdExplorerRouteImport } from './routes/api/admin/skd-explorer'
import { Route as ApiAdminSkdBatchesRouteImport } from './routes/api/admin/skd-batches'
import { Route as ApiAdminResultSessionsRouteImport } from './routes/api/admin/result-sessions'
import { Route as ApiAdminPdfSourcesRouteImport } from './routes/api/admin/pdf-sources'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaTokenRoute = WaTokenRouteImport.update({
  id: '/wa/$token',
  path: '/wa/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultScoreIdRoute = ResultScoreIdRouteImport.update({
  id: '/result/$scoreId',
  path: '/result/$scoreId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaResultRoute = ApiWaResultRouteImport.update({
  id: '/api/wa-result',
  path: '/api/wa-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaJobsRoute = ApiWaJobsRouteImport.update({
  id: '/api/wa-jobs',
  path: '/api/wa-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResultSessionRoute = ApiResultSessionRouteImport.update({
  id: '/api/result-session',
  path: '/api/result-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResultCardRoute = ApiResultCardRouteImport.update({
  id: '/api/result-card',
  path: '/api/result-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRationalizationTargetsRoute =
  ApiRationalizationTargetsRouteImport.update({
    id: '/api/rationalization-targets',
    path: '/api/rationalization-targets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSkdReviewRoute = ApiAdminSkdReviewRouteImport.update({
  id: '/api/admin/skd-review',
  path: '/api/admin/skd-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSkdPdfRoute = ApiAdminSkdPdfRouteImport.update({
  id: '/api/admin/skd-pdf',
  path: '/api/admin/skd-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSkdExplorerRoute = ApiAdminSkdExplorerRouteImport.update({
  id: '/api/admin/skd-explorer',
  path: '/api/admin/skd-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSkdBatchesRoute = ApiAdminSkdBatchesRouteImport.update({
  id: '/api/admin/skd-batches',
  path: '/api/admin/skd-batches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResultSessionsRoute = ApiAdminResultSessionsRouteImport.update({
  id: '/api/admin/result-sessions',
  path: '/api/admin/result-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPdfSourcesRoute = ApiAdminPdfSourcesRouteImport.update({
  id: '/api/admin/pdf-sources',
  path: '/api/admin/pdf-sources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/search': typeof SearchRoute
  '/api/rationalization-targets': typeof ApiRationalizationTargetsRoute
  '/api/result-card': typeof ApiResultCardRoute
  '/api/result-session': typeof ApiResultSessionRoute
  '/api/wa-jobs': typeof ApiWaJobsRoute
  '/api/wa-result': typeof ApiWaResultRoute
  '/result/$scoreId': typeof ResultScoreIdRoute
  '/wa/$token': typeof WaTokenRoute
  '/api/admin/pdf-sources': typeof ApiAdminPdfSourcesRoute
  '/api/admin/result-sessions': typeof ApiAdminResultSessionsRoute
  '/api/admin/skd-batches': typeof ApiAdminSkdBatchesRoute
  '/api/admin/skd-explorer': typeof ApiAdminSkdExplorerRoute
  '/api/admin/skd-pdf': typeof ApiAdminSkdPdfRoute
  '/api/admin/skd-review': typeof ApiAdminSkdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/search': typeof SearchRoute
  '/api/rationalization-targets': typeof ApiRationalizationTargetsRoute
  '/api/result-card': typeof ApiResultCardRoute
  '/api/result-session': typeof ApiResultSessionRoute
  '/api/wa-jobs': typeof ApiWaJobsRoute
  '/api/wa-result': typeof ApiWaResultRoute
  '/result/$scoreId': typeof ResultScoreIdRoute
  '/wa/$token': typeof WaTokenRoute
  '/api/admin/pdf-sources': typeof ApiAdminPdfSourcesRoute
  '/api/admin/result-sessions': typeof ApiAdminResultSessionsRoute
  '/api/admin/skd-batches': typeof ApiAdminSkdBatchesRoute
  '/api/admin/skd-explorer': typeof ApiAdminSkdExplorerRoute
  '/api/admin/skd-pdf': typeof ApiAdminSkdPdfRoute
  '/api/admin/skd-review': typeof ApiAdminSkdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/search': typeof SearchRoute
  '/api/rationalization-targets': typeof ApiRationalizationTargetsRoute
  '/api/result-card': typeof ApiResultCardRoute
  '/api/result-session': typeof ApiResultSessionRoute
  '/api/wa-jobs': typeof ApiWaJobsRoute
  '/api/wa-result': typeof ApiWaResultRoute
  '/result/$scoreId': typeof ResultScoreIdRoute
  '/wa/$token': typeof WaTokenRoute
  '/api/admin/pdf-sources': typeof ApiAdminPdfSourcesRoute
  '/api/admin/result-sessions': typeof ApiAdminResultSessionsRoute
  '/api/admin/skd-batches': typeof ApiAdminSkdBatchesRoute
  '/api/admin/skd-explorer': typeof ApiAdminSkdExplorerRoute
  '/api/admin/skd-pdf': typeof ApiAdminSkdPdfRoute
  '/api/admin/skd-review': typeof ApiAdminSkdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/search'
    | '/api/rationalization-targets'
    | '/api/result-card'
    | '/api/result-session'
    | '/api/wa-jobs'
    | '/api/wa-result'
    | '/result/$scoreId'
    | '/wa/$token'
    | '/api/admin/pdf-sources'
    | '/api/admin/result-sessions'
    | '/api/admin/skd-batches'
    | '/api/admin/skd-explorer'
    | '/api/admin/skd-pdf'
    | '/api/admin/skd-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/search'
    | '/api/rationalization-targets'
    | '/api/result-card'
    | '/api/result-session'
    | '/api/wa-jobs'
    | '/api/wa-result'
    | '/result/$scoreId'
    | '/wa/$token'
    | '/api/admin/pdf-sources'
    | '/api/admin/result-sessions'
    | '/api/admin/skd-batches'
    | '/api/admin/skd-explorer'
    | '/api/admin/skd-pdf'
    | '/api/admin/skd-review'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/search'
    | '/api/rationalization-targets'
    | '/api/result-card'
    | '/api/result-session'
    | '/api/wa-jobs'
    | '/api/wa-result'
    | '/result/$scoreId'
    | '/wa/$token'
    | '/api/admin/pdf-sources'
    | '/api/admin/result-sessions'
    | '/api/admin/skd-batches'
    | '/api/admin/skd-explorer'
    | '/api/admin/skd-pdf'
    | '/api/admin/skd-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SearchRoute: typeof SearchRoute
  ApiRationalizationTargetsRoute: typeof ApiRationalizationTargetsRoute
  ApiResultCardRoute: typeof ApiResultCardRoute
  ApiResultSessionRoute: typeof ApiResultSessionRoute
  ApiWaJobsRoute: typeof ApiWaJobsRoute
  ApiWaResultRoute: typeof ApiWaResultRoute
  ResultScoreIdRoute: typeof ResultScoreIdRoute
  WaTokenRoute: typeof WaTokenRoute
  ApiAdminPdfSourcesRoute: typeof ApiAdminPdfSourcesRoute
  ApiAdminResultSessionsRoute: typeof ApiAdminResultSessionsRoute
  ApiAdminSkdBatchesRoute: typeof ApiAdminSkdBatchesRoute
  ApiAdminSkdExplorerRoute: typeof ApiAdminSkdExplorerRoute
  ApiAdminSkdPdfRoute: typeof ApiAdminSkdPdfRoute
  ApiAdminSkdReviewRoute: typeof ApiAdminSkdReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wa/$token': {
      id: '/wa/$token'
      path: '/wa/$token'
      fullPath: '/wa/$token'
      preLoaderRoute: typeof WaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$scoreId': {
      id: '/result/$scoreId'
      path: '/result/$scoreId'
      fullPath: '/result/$scoreId'
      preLoaderRoute: typeof ResultScoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-result': {
      id: '/api/wa-result'
      path: '/api/wa-result'
      fullPath: '/api/wa-result'
      preLoaderRoute: typeof ApiWaResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-jobs': {
      id: '/api/wa-jobs'
      path: '/api/wa-jobs'
      fullPath: '/api/wa-jobs'
      preLoaderRoute: typeof ApiWaJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/result-session': {
      id: '/api/result-session'
      path: '/api/result-session'
      fullPath: '/api/result-session'
      preLoaderRoute: typeof ApiResultSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/result-card': {
      id: '/api/result-card'
      path: '/api/result-card'
      fullPath: '/api/result-card'
      preLoaderRoute: typeof ApiResultCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rationalization-targets': {
      id: '/api/rationalization-targets'
      path: '/api/rationalization-targets'
      fullPath: '/api/rationalization-targets'
      preLoaderRoute: typeof ApiRationalizationTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/skd-review': {
      id: '/api/admin/skd-review'
      path: '/api/admin/skd-review'
      fullPath: '/api/admin/skd-review'
      preLoaderRoute: typeof ApiAdminSkdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/skd-pdf': {
      id: '/api/admin/skd-pdf'
      path: '/api/admin/skd-pdf'
      fullPath: '/api/admin/skd-pdf'
      preLoaderRoute: typeof ApiAdminSkdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/skd-explorer': {
      id: '/api/admin/skd-explorer'
      path: '/api/admin/skd-explorer'
      fullPath: '/api/admin/skd-explorer'
      preLoaderRoute: typeof ApiAdminSkdExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/skd-batches': {
      id: '/api/admin/skd-batches'
      path: '/api/admin/skd-batches'
      fullPath: '/api/admin/skd-batches'
      preLoaderRoute: typeof ApiAdminSkdBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/result-sessions': {
      id: '/api/admin/result-sessions'
      path: '/api/admin/result-sessions'
      fullPath: '/api/admin/result-sessions'
      preLoaderRoute: typeof ApiAdminResultSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pdf-sources': {
      id: '/api/admin/pdf-sources'
      path: '/api/admin/pdf-sources'
      fullPath: '/api/admin/pdf-sources'
      preLoaderRoute: typeof ApiAdminPdfSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SearchRoute: SearchRoute,
  ApiRationalizationTargetsRoute: ApiRationalizationTargetsRoute,
  ApiResultCardRoute: ApiResultCardRoute,
  ApiResultSessionRoute: ApiResultSessionRoute,
  ApiWaJobsRoute: ApiWaJobsRoute,
  ApiWaResultRoute: ApiWaResultRoute,
  ResultScoreIdRoute: ResultScoreIdRoute,
  WaTokenRoute: WaTokenRoute,
  ApiAdminPdfSourcesRoute: ApiAdminPdfSourcesRoute,
  ApiAdminResultSessionsRoute: ApiAdminResultSessionsRoute,
  ApiAdminSkdBatchesRoute: ApiAdminSkdBatchesRoute,
  ApiAdminSkdExplorerRoute: ApiAdminSkdExplorerRoute,
  ApiAdminSkdPdfRoute: ApiAdminSkdPdfRoute,
  ApiAdminSkdReviewRoute: ApiAdminSkdReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
